final Map<String, String> plantCategory = {
  "tomato": "Vegetable Plants",
  "cucumber": "Vegetable Plants",
  "eggplant": "Vegetable Plants",
  "mint": "Herbal Plants",
  "basil": "Herbal Plants",
  "date palm": "Fruit Trees",
  "lemon": "Fruit Trees",
  "rose": "Flowering Plants",
  "hibiscus": "Flowering Plants",
  "bougainvillea":"Flowering Plants",
  "broccoli":"Vegetable Plants",
  "cabbage":"Vegetable Plants",
  "carrot":"Vegetable Plants",
  "dessert rose":"Flowering Plants",
  "dill":"Herbal Plants",
  "mango":"Fruit Trees",
  "parsley":"Herbal Plants",
  "potato":"Vegetable Plants",
  "sage":"Herbal Plants",
  "apple":"Fruit Trees",
  "Banana Tree":"Fruit Trees",
  "Garlic":"Vegetable Plants",
  "Jasmine":"Flowering Plants",
  "Pomegranate":"Fruit Trees"
};
